name: ez_money_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  awesome_dialog: ^3.2.1
  bloc: ^8.1.4
  carousel_slider: ^5.0.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localization: ^0.2.2
  flutter_svg: ^2.0.11
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.7
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.1.3
  path_provider: ^2.1.5
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  syncfusion_flutter_charts: ^27.2.5
  syncfusion_flutter_datepicker: ^27.2.5

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
